JAVAC = javac


JFLAGS = -g


SOURCES = Main.java Centre.java Employé.java EmployéEdt.java Mission.java CSVReader.java CoupleEmployéMission.java Kmeans.java AlgoTabou.java


default: compile


compile:
    $(JAVAC) $(JFLAGS) $(SOURCES)


clean:
    rm -f *.class